use_frameworks!
source 'https://github.com/marceCuevas16/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AnotherChildPod_Example' do
  pod 'AnotherChildPod', :path => '../'

  target 'AnotherChildPod_Tests' do
    inherit! :search_paths

    
  end
end
